[package]
name = "bitfenix-icon-sysstatus"
version = "0.1.0"
authors = ["Avishkar Autar <aautar@digital-radiation.com>"]

[dependencies]
png = "0.15.3"
hidapi = "1.1.0"
systemstat = "0.2.3"
hostname = "^0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4.31"
